### ISSUE TITLE
Commands output as reply to request instead of to stdout

### ISSUE THREAD

**Issue by Adam7288** [hyper-prog/hasses#10]
Would be great if there could be an option to get statistics, or a list of clients, for instance as a reply to a request on port 8085 instead of directing the output to stdout.

To get the output of these commands involves a lot of engineering in order to pull the response from the logs.

**Comment by hyper-prog** [comment]
Solved by creating new commands with tcp prefix: 
"tcpstatus", "tcpnumberofclients", "tcpsubscribedclients:<sub>"
