### ISSUE TITLE
Performance improvement: hash table for subscriptions with pointers to CliConn objects

### ISSUE THREAD

**Issue by Adam7288** [hyper-prog/hasses#12]
Instead of traversing all clients to check if they are subscribed for each message, this will greatly improve performance

**Comment by hyper-prog** [comment]
Yes, It may bring some performance when sending messages but it needs more performance when managing clients (connect, disconnect) 
Did you experienced some bottleneck here, or just think about it?

**Comment by Adam7288** [comment]
Yes just thinking. And yes I did notice the performance of the connect and disconnect is quite bad and unworkable for production.
