### ISSUE TITLE
delete an in-progress SSE streaming request.

### ISSUE THREAD

**Issue by farhanz** [hyper-prog/hasses#2]
Is there an option to delete SSE connection?
Scenario:

Client has opened SSE streaming (GET /sse?subscribe=XXX&id=ABCD1234)
Client should be able to issue a delete on the existing streaming (DELETE /sse?id=ABCD1234)

**Comment by hyper-prog** [comment]
You should open the SSE connection through javascript EventSource object,
thus you have to call EventSource's close() method to close sse connection.
https://developer.mozilla.org/en-US/docs/Web/API/EventSource
