### ISSUE TITLE
Beginners help?

### ISSUE THREAD

**Issue by gaaloe** [hyper-prog/hasses#9]
I would like to try out hasses, but there are no instructions on how to run a minimal trial setup. The git-clone and compilation runs OK.
The reason I download hasses it is to investigate how SSE is done using C code in the server. The w3school is not very helpful on this. I see that hasses makes a successful text/event-stream message in C code. I have had good use of this as a sourcecode example for my project, but I would like it to execute as well.
Am I supposed to use the Docker container? I hope the source code is sufficient, and the Docker can be opted out? (I have dropped Docker as a tool).

**Comment by hyper-prog** [comment]
Hello!

I recommend you to use the docker-compose example which creates a minimal
working environment for you
https://github.com/hyper-prog/hasses/tree/master/EXAMPLES/complex_docker_compose
Anyway If your purpose is to study the sse in server side, I don't think
the hasses is ideal project for you.
A lot easier to create a single SSE server than hasses do, because the
hasses run in assinchron mode to handle many clients without performance
loss.
I encourage you to use docker. It does not affect the working of hasses but
makes it easier to build the environment.

Bye
Peter

**Comment by gaaloe** [comment]
The Docker version does not run. Web_srv was unavailable.
--
Skickat från myMail för Android måndag, 10 oktober 2022, 09:42AM +02:00 från Péter Deák  ***@***.*** :

>Hello!
>
>I recommend you to use the docker-compose example which creates a minimal
>working environment for you
>https://github.com/hyper-prog/hasses/tree/master/EXAMPLES/complex_docker_compose
>Anyway If your purpose is to study the sse in server side, I don't think
>the hasses is ideal project for you.
>A lot easier to create a single SSE server than hasses do, because the
>hasses run in assinchron mode to handle many clients without performance
>loss.
>I encourage you to use docker. It does not affect the working of hasses but
>makes it easier to build the environment.
>
>Bye
>Peter
>

**Comment by hyper-prog** [comment]
It works flawless on a fresh installed debian bullseye:

***@***.***:~/TEST# *git clone https://github.com/hyper-prog/hasses
<https://github.com/hyper-prog/hasses>*
Cloning into 'hasses'...
remote: Enumerating objects: 148, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 148 (delta 24), reused 26 (delta 12), pack-reused 96
Receiving objects: 100% (148/148), 276.33 KiB | 3.41 MiB/s, done.
Resolving deltas: 100% (57/57), done.

***@***.***:~/TEST# *cd hasses/EXAMPLES/complex_docker_compose/*

***@***.***:~/TEST/hasses/EXAMPLES/complex_docker_compose# *docker-compose
up -d*
Creating network "complex_docker_compose_default" with the default driver
Pulling hassesdaemon (hyperprog/hassesdaemon:)...
latest: Pulling from hyperprog/hassesdaemon
59bf1c3509f3: Pull complete
ad8ff6506ea6: Pull complete
91653440b591: Pull complete
Digest:
sha256:781ebf5b0729baafd9b5761de37f8cb2912c90b4bdf6e075bcf90529ac204f08
Status: Downloaded newer image for hyperprog/hassesdaemon:latest
Pulling webchat (hyperprog/codkepalpine:)...
latest: Pulling from hyperprog/codkepalpine
213ec9aee27d: Pull complete
afd9886919c5: Pull complete
269930bd8fdc: Pull complete
0ac95f7529ec: Pull complete
88aace1c0702: Pull complete
5e77a2b0687a: Pull complete
Digest:
sha256:518b00b2b9a414a27ac2aede8638e658bd8db4cf25dcf5867d71dae1a871ba1c
Status: Downloaded newer image for hyperprog/codkepalpine:latest
Creating hasses_srv ... done
Creating web_srv    ... done

***@***.***:~/TEST/hasses/EXAMPLES/complex_docker_compose# *curl
http://127.0.0.1 <http://127.0.0.1>*
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title></title>
...

***@***.***:~/TEST/hasses/EXAMPLES/complex_docker_compose# *docker ps*
CONTAINER ID   IMAGE                    COMMAND                  CREATED
           STATUS              PORTS                              NAMES
95251b9a45be   hyperprog/codkepalpine   "/usr/sbin/httpd -D …"   About a
minute ago   Up About a minute   0.0.0.0:80->80/tcp                 web_srv
9b939b3ce585   hyperprog/hassesdaemon   "/usr/local/bin/hass…"   About a
minute ago   Up About a minute   0.0.0.0:8080->8080/tcp, 8085/tcp
hasses_srv

**Comment by gaaloe** [comment]
henrik@Adler:~/hasses/EXAMPLES/complex_docker_compose$ docker-compose up -d
hasses_srv is up-to-date
Starting web_srv ... 
Starting web_srv ... error

ERROR: for web_srv  Cannot start service webchat: driver failed programming external connectivity on endpoint web_srv (3f9ac6419dac268d2250bc628a7e502257eb671cc04d7c1ce71f3e72dcd95675): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

ERROR: for webchat  Cannot start service webchat: driver failed programming external connectivity on endpoint web_srv (3f9ac6419dac268d2250bc628a7e502257eb671cc04d7c1ce71f3e72dcd95675): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by hyper-prog** [comment]
"*listen tcp4 0.0.0.0:80 <http://0.0.0.0/>: bind: address already in use*"
The web service cannot start because your tcp port is used by another
program (probable by a web server)
Stop your web server or other programs which use tcp port 80
(By the way this problem is does not related to hasses)

**Comment by gaaloe** [comment]
OK, it was an Apache server running on port 80. After it was stopped, the web_srv started OK. Now there are docker-proxy serving the port 80 and 8080. What do I do now? I would like to see some SSE action.

**Comment by hyper-prog** [comment]
Open your computer's web port with a browser. Open with more browser (or
host) same time.
It's a web based chat program which works without database. The messages
are transferrwd with sse.

On Wednesday, October 19, 2022, gaaloe ***@***.***> wrote:
> OK, it was an Apache server running on port 80. After it was stopped, the
web_srv started OK. Now there are docker-proxy serving the port 80 and
8080. What do I do now? I would like to see some SSE action.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.<
https://ci5.googleusercontent.com/proxy/2zbyXpueOtc58pra3UQCGm-AjHHuX3sJ7SkB7G_B18boCSa_VTTEBrCa-pVhE50fdm3f_kTIct0KDlgtIbbbq-qMZFwVsEPVrlgkyGMmMPheIP-NMBXS1ose-mL037Z3BHqz5JrSuhVgTKF82ipYkqpq39Np1N7EgUZVJZIa9NJL9Y6fTYeHyjLED7ezVii95tHoM1lRrdBbC_XkIQd0wBsrRAE-WSHa_ReJBvye3hfbB8VU1Q=s0-d-e1-ft#https://github.com/notifications/beacon/AH45JEVN33YHJJ4JBI6K5J3WEACGNA5CNFSM6AAAAAARARTPOWWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSMRJBJW.gif>Message
ID: ***@***.***>

**Comment by gaaloe** [comment]
OK, after stopping the Apache and starting the docker containers, I opened URL http://localhost:80/ from two separate browsers, and the chat was up and running using C-coded SSE! A few lines from this Issue conversation should reside somewhere as text in this repository, and others would benefit greatly.
